import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="origin-trial"
          content="Ai4sGfKvDNSnHsE0u/j93ArJsHlNP2o8K8jELHtICg71Vf55VhV2prFL9va3Y99VG8S4GtJWTKwFHbcerUEncQgAAABreyJvcmlnaW4iOiJodHRwczovL2Nocm9tZS1haS10ZXh0LXByb2Nlc3Nvci52ZXJjZWwuYXBwOjQ0MyIsImZlYXR1cmUiOiJUcmFuc2xhdGlvbkFQSSIsImV4cGlyeSI6MTc1MzE0MjQwMH0="
        />
        <meta
          httpEquiv="origin-trial"
          content="AvWtCPJk9bIqMpPCodGV0DCx21cUaeEHpS7gXmaUv0zFL0VXrD4K9tSpN4yj/THgxEfwGyzkq8RjgfkdGSmTNQQAAABxeyJvcmlnaW4iOiJodHRwczovL2Nocm9tZS1haS10ZXh0LXByb2Nlc3Nvci52ZXJjZWwuYXBwOjQ0MyIsImZlYXR1cmUiOiJMYW5ndWFnZURldGVjdGlvbkFQSSIsImV4cGlyeSI6MTc0OTU5OTk5OX0="
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
